{
 "title": "PETROLEO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "COSTA RICA" ],
       "text": "setAlias(COSTA RICA)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-CR" },
     "item": { "filter": "Temperatura" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CHAPADAO" ],
       "text": "setAlias(CHAPADAO)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-CHA" },
     "item": { "filter": "Temperatura" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "TAQUARI" ],
       "text": "setAlias(TAQUARI)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-A.T" },
     "item": { "filter": "Temperatura" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "G.N.H" ],
       "text": "setAlias(G.N.H)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-G.N.H" },
     "item": { "filter": "Temperatura" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "SAO FELIX" ],
       "text": "setAlias(SAO FELIX)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-S.F" },
     "item": { "filter": "Temperatura" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ZABBIX RAM USO",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "format": "percent",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Memory utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ZABBIX CPU USO",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "format": "percent",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPU PET CR" ],
       "text": "setAlias(CPU PET CR)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-CR" },
     "item": { "filter": "CPU Load" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPU PET CH" ],
       "text": "setAlias(CPU PET CH)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-CHA" },
     "item": { "filter": "CPU Load" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPU PET TQ" ],
       "text": "setAlias(CPU PET TQ)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-A.T" },
     "item": { "filter": "CPU Load" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPU PET GNH" ],
       "text": "setAlias(CPU PET GNH)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-G.N.H" },
     "item": { "filter": "CPU Load" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPU PET SF" ],
       "text": "setAlias(CPU PET SF)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-S.F" },
     "item": { "filter": "CPU Load" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SVR PETROLEO UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "RAM USO" ],
       "text": "setAlias(RAM USO)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": { "filter": "Physical Memory: Used memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "RAM TOTAL" ],
       "text": "setAlias(RAM TOTAL)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": { "filter": "Physical Memory: Total memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU EM USO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM EM USO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": {
      "filter": "Physical Memory: Memory utilization"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "C: UTILIZAÇÃO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": {
      "filter": "C:\\ Label:  Serial Number ae0bdf65: Space utilization"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "D: UTILIZAÇÃO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": {
      "filter": "D:\\ Label:FTP  Serial Number 4e0d5408: Space utilization"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "C: USO" ],
       "text": "setAlias(C: USO)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": {
      "filter": "C:\\ Label:  Serial Number ae0bdf65: Used space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "C: TOTAL" ],
       "text": "setAlias(C: TOTAL)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": {
      "filter": "C:\\ Label:  Serial Number ae0bdf65: Total space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "D: TOTAL" ],
       "text": "setAlias(D: TOTAL)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": {
      "filter": "D:\\ Label:FTP  Serial Number 4e0d5408: Used space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "D: TOTAL" ],
       "text": "setAlias(D: TOTAL)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-PETROLEO" },
     "item": {
      "filter": "D:\\ Label:FTP  Serial Number 4e0d5408: Total space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PING  DNS GOOGLE",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "DNS" },
     "host": { "filter": "GOOGLE" },
     "item": { "filter": "Tempo de Resposta" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PING  PET. COSTA RICA",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-CR" },
     "item": { "filter": "Tempo de Resposta" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PING PET. CHAPADAO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-CHA" },
     "item": { "filter": "Tempo de Resposta" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PING PET. TAQUARI",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-A.T" },
     "item": { "filter": "Tempo de Resposta" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PING  PET. GNH",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-G.N.H" },
     "item": { "filter": "Tempo de Resposta" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PING PET. SAO FELIX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-S.F" },
     "item": { "filter": "Tempo de Resposta" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SVR GNH UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU EM USO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM EM USO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": {
      "filter": "Physical Memory: Memory utilization"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "C: UTILIZAÇÃO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": {
      "filter": "C:\\ Label:  Serial Number 186b7a70: Space utilization"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "M: UTILIZAÇÃO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": {
      "filter": "M:\\ Label:DADOS  Serial Number 2439aa5a: Space utilization"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "RAM USO" ],
       "text": "setAlias(RAM USO)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": { "filter": "Physical Memory: Used memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "RAM TOTAL" ],
       "text": "setAlias(RAM TOTAL)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": { "filter": "Physical Memory: Total memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "C: USO" ],
       "text": "setAlias(C: USO)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": {
      "filter": "C:\\ Label:  Serial Number 186b7a70: Used space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "C: TOTAL" ],
       "text": "setAlias(C: TOTAL)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": {
      "filter": "C:\\ Label:  Serial Number 186b7a70: Total space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "M: USO" ],
       "text": "setAlias(M: USO)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": {
      "filter": "M:\\ Label:DADOS  Serial Number 2439aa5a: Used space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "M: TOTAL" ],
       "text": "setAlias(M: TOTAL)"
      }
     ],
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "SVR-GNH" },
     "item": {
      "filter": "M:\\ Label:DADOS  Serial Number 2439aa5a: Total space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ALERTAS",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ZABBIX ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "/: Used space" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "/: Total space" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TRÁFEGO LINK PETROLEO COSTA RICA",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-CR" },
     "item": {
      "filter": "Interface ether1(SPEEDNETCR): Tráf. Entrada"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "PETROLEO" },
     "host": { "filter": "RB-PET-CR" },
     "item": {
      "filter": "Interface ether1(SPEEDNETCR): Tráf. Saída"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}